# Generated by Django 3.2.5 on 2023-02-27 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=40, verbose_name='単語')),
                ('description', models.CharField(max_length=200, verbose_name='説明')),
            ],
        ),
    ]
